[platformio]
src_dir = ESP32-HW3

[env:waveshare_ESP32_S3_RS485_CAN]
platform = espressif32
board = esp32s3box
framework = arduino
build_flags =
    -DTWAI_TX_PIN=GPIO_NUM_15
    -DTWAI_RX_PIN=GPIO_NUM_16
    -DTWAI_RX_QUEUE_LEN=64
    -DTWAI_TX_QUEUE_LEN=16
